### ISSUE TITLE
Location indicator not visible in Kakoune v2019.12.10

### ISSUE THREAD

**Issue by fsub** [occivink/kakoune-gdb#15]
The location indicator is not visible in Kakoune v2019.12.10.
The problem does not occur in Kakoune v2019.07.01.

**Comment by fsub** [comment]
The issue was introduced by the following commit:
https://github.com/mawww/kakoune/commit/0e4a4acf61dbcd1e025810f8e67aca2eaeb44e19

**Comment by occivink** [comment]
I'm on `v2019.12.10-5-gb9823718` and everything seems to work fine, is there anything in the *debug* buffer?

**Comment by fsub** [comment]
*** This is the debug buffer, where debug info will be written ***
[gdb][kak] gdb-cmd -gdb-exit
[gdb][kak] gdb-cmd -exec-arguments ␤ -exec-run --start

**Comment by fsub** [comment]
It works for me if I unset `XDG_RUNTIME_DIR`.

**Comment by fsub** [comment]
If `XDG_RUNTIME_DIR` is unset the debug buffer contains:
*** This is the debug buffer, where debug info will be written ***
[gdb][kak] gdb-cmd -gdb-exit
[gdb][kak] gdb-cmd -exec-arguments ␤ -exec-run --start
[gdb][kak] gdb-handle-breakpoint-created 1 y 26 /tmp/hello.cxx
[gdb][kak] gdb-refresh-breakpoints-flags /tmp/hello.cxx
[gdb][kak] gdb-handle-breakpoint-modified 1 y 26 /tmp/hello.cxx
[gdb][kak] gdb-refresh-breakpoints-flags /tmp/hello.cxx
[gdb][kak] gdb-handle-running
[gdb][kak] gdb-clear-location
[gdb][kak] gdb-clear-breakpoints
[gdb][kak] gdb-handle-breakpoint-created 1 y 26 /tmp/hello.cxx
[gdb][kak] gdb-refresh-breakpoints-flags /tmp/hello.cxx
[gdb][error] Selected thread is running.
[gdb][kak] gdb-handle-breakpoint-modified 1 y 26 /tmp/hello.cxx
[gdb][kak] gdb-refresh-breakpoints-flags /tmp/hello.cxx
[gdb][kak] gdb-handle-stopped 26 /tmp/hello.cxx
[gdb][kak] gdb-process-pending-commands
[gdb][kak] gdb-refresh-location-flag /tmp/hello.cxx
[gdb][kak] gdb-handle-breakpoint-deleted 1
[gdb][kak] gdb-refresh-breakpoints-flags /tmp/hello.cxx

**Comment by fsub** [comment]
The problem materialized due to unfortunate circumstances: I was using a manually compiled `kak` binary located in some private directory. `kakoune-gdb` called my old `kak` binary from `bin`.
Probably, kakoune should provide an environment variable `kak_binary_path` so that the usual pattern `kak -p $kak_session` can be improved to `$kak_binary_path -p $kak_session`.
