### ISSUE TITLE
Provide information whether program is running

### ISSUE THREAD

**Issue by fsub** [occivink/kakoune-gdb#4]
Information whether there is a program running is valuable.

Use case: Define a command that either calls gdb-run or gdb-continue depending on the situation. (See F5 in Visual Studio and Qt Creator.)

**Comment by occivink** [comment]
If you feel like making a PR for `start-or-continue`, and `run-or-continue` I'd merge it

**Comment by fsub** [comment]
Do we need to support arguments?

For my use case, this how I extended `kakrc`:
```
define-command dbg-run-or-continue \
   -docstring %(dbg: run/continue program) \
%{
   %sh{
      if [ "${kak_opt_gdb_program_running}" = true ]; then
         printf "gdb-continue\n"
      else
         printf "gdb-run\n"
      fi
   }
}
```

**Comment by occivink** [comment]
Thanks, I'll add this if you don't mind. This also reminds me I should write some proper docstrings

**Comment by fsub** [comment]
Sure, just take it.
